@dotnet_notification_service_HostAddress = http://localhost:5143

GET {{dotnet_notification_service_HostAddress}}/weatherforecast/
Accept: application/json

### Create new user
POST {{dotnet_notification_service_HostAddress}}/api/v1.0/Auth
Content-Type: application/json

{
    "Email": "daniel1@test.com",
    "Password": "Daniel"
}
