@dotnet_notification_service_HostAddress = http://localhost:5143
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJkb3RuZXQtbm90aWZpY2F0aW9uLXNlcnZpY2UtYXVkaWVuY2UiLCJpc3MiOiJkb3RuZXQtbm90aWZpY2F0aW9uLXNlcnZpY2UiLCJleHAiOjE3NzA2NTk4ODUsInN1YiI6IjAxS0gxSFpNWVFKOEs3UlRQMUUyN05RMEFTIiwiZW1haWwiOiJkYW5pZWw3QHRlc3QuY29tIiwiZW1haWxfdmVyaWZpZWQiOiJ0cnVlIiwiaWF0IjoxNzcwNjUyNjg1LCJuYmYiOjE3NzA2NTI2ODV9.n-bazZRqDn1ut9hEE2zfP_-1-w1M0D0gKPoP5_45-iE


### Create new user
POST {{dotnet_notification_service_HostAddress}}/api/v1.0/Auth
Content-Type: application/json

{
    "Email": "daniel7@test.com",
    "Password": "Daniel"
}

### Post new notification (include Authorization header)
POST {{dotnet_notification_service_HostAddress}}/api/v1.0/Notifications
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "Type": "email",
    "Title": "Test Notification 5",
    "Content": "This is a test notification message.",
    "Recipient": "danireysan@gmail.com"
}

### Update notification (include Authorization header)
PUT {{dotnet_notification_service_HostAddress}}/api/v1.0/Notifications/
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "Type": "email",
    "Id": "01KH09CDFEFR3NWA79C0BERR3E",
    "Title": "Updated Test Notification HEY 6",
    "Content": "This is  message. WAWAW",
    "Recipient": "asdfasdfasdf"
}

### Get all notifications (include Authorization header)
GET {{dotnet_notification_service_HostAddress}}/api/v1.0/Notifications
Authorization: Bearer {{jwt}}

### Delete notification (include Authorization header)
DELETE {{dotnet_notification_service_HostAddress}}/api/v1.0/Notifications/01KH09CDFEFR3NWA79C0BERR3E
Content-Type: application/json
Authorization: Bearer {{jwt}}


